### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by idevelopr** [misa198/scdl-core#2]
TypeError: Cannot read property '0' of undefined
    at step (C:\Users\Downloads\Test\node_modules\scdl-core\dist\services\playlist.js:20:23)
    at Object.throw (C:\Users\Downloads\Test\node_modules\scdl-core\dist\services\playlist.js:14:53)
    at rejected (C:\Users\Downloads\Test\node_modules\scdl-core\dist\services\playlist.js:6:65)

The above error can easily be replicated with the below code 

`async function test() {
    try {
        const playlist = scdl.connect().then(() =>
            scdl.playlists.getPlaylist("https://soundcloud.com/sertac-sayrin/sets/pisiko-trap-elektro")
                .then((data) => {
                    console.log(data)
                }))
    } catch (error) {
        console.error(error)
    }`

**Comment by misa198** [comment]
Hello.
Thanks for reporting the problem. I fixed that in 1.0.20.

**Comment by misa198** [comment]
Hello. Thanks for reporting the issue. I fixed that in 1.0.20.
